server:
  port: 8080
forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 60000        # 连接超时时间，单位为毫秒
  read-timeout: 60000           # 数据读取超时时间，单位为毫秒

park:
  code:
    url: https://s.keytop.cn/d13wez

liteflow:
  rule-source: config/flow.xml