server:
  port: 9090
forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 60000        # 连接超时时间，单位为毫秒
  read-timeout: 60000           # 数据读取超时时间，单位为毫秒

gobrs:
  async:
    config:
      rules:
        # 规则 是数组类型的 多组规则
        - name: "ruleName"
          content: "AService,BService;"
          transaction: true